# fly.toml app configuration file generated for nfvdpan on 2023-10-04T18:00:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nfvdpan"
primary_region = "sin"

[mounts]
  source="alist_data"
  destination="/opt/alist/data"

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
